#!/usr/bin/env bash
set -euo pipefail

# installing chromium browser to enable webpdf conversion using nbconvert
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
playwright install chromium

# https://github.com/berkeley-dsep-infra/datahub/issues/5827
git config --system pull.rebase false

# overrides.json is a file that jupyterlab reads to determine some settings
# 1) remove the 'create shareable link' option from the filebrowser context menu
mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
cp -p overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings

# code-server's conda package assets are installed in share/code-server.
export VSCODE_EXTENSIONS=${CONDA_DIR}/envs/notebook/share/code-server/extensions
mkdir -p ${VSCODE_EXTENSIONS}

# This is not reproducible, and it can be difficult to version these.
for x in \
  ms-toolsai.jupyter \
  ms-python.python \
  quarto.quarto \
  ms-vscode.live-server \
  posit.shiny \
  reditorsupport.r \
  ; do
    code-server --extensions-dir ${VSCODE_EXTENSIONS} --install-extension $x
done
